#端口号
server:
  port: 9082
#服务名和数据源(连接池)
spring:
  application:
    name: ssservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cz_health_base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka